const events = [
    'plotly_click',
    'plotly_hover',
    'plotly_unhover',
    'plotly_selecting',
    'plotly_selected',
    'plotly_restyle',
    'plotly_relayout',
    'plotly_relayouting',
    'plotly_clickannotation',
    'plotly_animatingframe',
    'plotly_legendclick',
    'plotly_legenddoubleclick',
    'plotly_sliderchange',
    'plotly_sliderend',
    'plotly_sliderstart',
    'plotly_sunburstclick',
    'plotly_event',
    'plotly_beforeplot',
    'plotly_afterexport',
    'plotly_afterplot',
    'plotly_animated',
    'plotly_animationinterrupted',
    'plotly_autosize',
    'plotly_beforeexport',
    'plotly_deselect',
    'plotly_doubleclick',
    'plotly_framework',
    'plotly_redraw',
    'plotly_transitioning',
    'plotly_transitioninterrupted',
]

export default events